### ISSUE TITLE
Basic import of Spatial Genomics 'genePS' seqFISH data into a SpatialExperiment object

### ISSUE THREAD

**Issue by methornton** [estellad/SpatialExperimentIO#3]
Hello!

I have some seqFISH data from Spatial Genomics generated by their 'genePS' system. I was wondering if anyone had some code to import this data into a SpatialExperiment S4 R/Bioconductor class object? It seems like the import functions were developed for the 10X Visium. I asked this on the SpatialExperiment github page and they suggested I ask it here.

I did find a tutorial from a Hackathon, but it was for multimodal data and required the data to be run through smfish-hmrf, which would be ideal normally. I don't have the extra information to use it. 

I also posted this on the Bioconductor support website, here, []https://support.bioconductor.org/p/9159361/(url)

The output data per ROI is in three CSV files which are structured like this:
```

    *_CellCoordinates.csv
    label,area,center_x,center_y
    1,4293,23720,1512
    2,6549,24498,1530
    3,2670,23152,1514
    4,4639,23537,1515
    
    *_CellxGene.csv
    	ITGB1	NR4A1	THBS1	HIF1A	******    ID2	CD37	DUSP2	ETS1  (600 gene entries)	
    1	0	0	2	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	1	0	0	0	0	0	0	0	0	0	0	
    2	0	1	0	0	0	0	0	0	0	0	0	3	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	
    3	0	0	1	0	0	0	0	1	1	0	0	1	0	0	1	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	1	0	0	1	0	1	0	0	0	1	0	0	0	0	
    
    *TranscriptList.csv
    name,x,y,z
    ITGB1,13841,3777,1
    ITGB1,13850,3773,1
    ITGB1,14866,3292,1
    ITGB1,14894,3774,1


```
This was all I was given to work with (so far). I will track down the images for all 7 ROI. Any advice or information that you can share with me is greatly appreciated. Thank you.

**Comment by estellad** [comment]
Hi Matt, 

Thanks for reaching out! The output files are all in .csv format, which can be easily converted to SPE class. I will have some time early next week to implement this :). Could you please provide me some subsetted toy.csv to experiment with? Or a link to the public seqFISH data download page? I will start with what you provided above, but I would like to test, just in case there are extra columns from the data download. 

Sincerely,
Estella

**Comment by methornton** [comment]
@estellad Hi!  Sure thank you! The data is pretty close to Vizgen.  I used the builtin 'readMerscopeSXE' but it didn't quite get it. It's probably a format issue. here is the [data](https://nep.saban-chla.usc.edu/bamfiles/test/) I really appreciate your help. Is there anyway to import the images and extract the segmentation data? 

```
> ls
[1] "TestSet_CellxGene.csv"    ## cell_by_gene    
[2] "TestSet_CellCoordinates.csv" ## cell_metadata       
[3] "TestSet_TranscriptList.csv"
> test <- readMerscopeSXE(dirname = '//24Jul24/convert/', return_type = "SPE", countmatfpattern = "CellxGene.csv", metadatafpattern = "CellCoordinates.csv", coord_names = c("center_x", "center_y"))
Error in order(countmat$cell) : argument 1 is not a vector
```
I had to change some of the names and paths. Please let me know when you have the data so I can take it off the web. Thank you very much!

Matt

**Comment by estellad** [comment]
Hi Matt,

Importing image and automating segmentation is currently not supported by SpatialExperimentIO, which aims at storing cellular resolution data as SPE class. To deal with image information, I would recommend Python framework, such as SpatialData. However, I am not sure if SpatialData have already implemented the technology you are working with. If it's similar to Vizgen, you could probably give SpatialData a try. 

I have downloaded the example data you provided. You can off load it now :)


Sincerely,
Estella

**Comment by methornton** [comment]
@estellad Thank you!  I have been looking at 'spatialexperiment-io' which is part of scverse.  However, the data I have is the newest iteration and not similar to  the example data that the company hosts (yet).  I really appreciate your efforts.

**Comment by estellad** [comment]
Hi Matt,

Sorry for the delay. I am at a conference. I have added the new reader function `readSeqfishSXE()` to the package, and updated README, vignette, tests for this function. If you run the following code. you should be able to get a SpatialExperiment object. Please let me know if it works!

```
devtools::install_github("estellad/SpatialExperimentIO")
path <- "~/Downloads"
library(SpatialExperimentIO)
spe <- readSeqfishSXE(path, return_type = "SPE"); spe
# class: SpatialExperiment 
# dim: 493 38314 
# metadata(0):
#   assays(1): counts
# rownames(493): ITGB1 NR4A1 ... FN1 COL3A1
# rowData names(0):
#   colnames(38314): 1 2 ... 38313 38314
# colData names(2): area sample_id
# reducedDimNames(0):
#   mainExpName: NULL
# altExpNames(0):
#   spatialCoords names(2) : center_x center_y
# imgData names(0):
```

**Comment by methornton** [comment]
Thank you again!  I really appreciate your help.
